import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by Onlook'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en" data-oid="allzcvr">
            <body className="" data-oid="nevsx56">
                {children}</body>
        </html>;
}